// src/app/layout.tsx

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/app/components/Header'
import { ClientLayout } from './ClientLayout' // 👈 Header 컴포넌트 불러오기

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'BookTree',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body>
                <Header />
                <main className="pt-[60px]">
                    {' '}
                    {/* Header 높이만큼 상단 패딩 추가 */}
                    {children}
                </main>
            </body>
        </html>
    )
}
