// src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header"; 
import { ClientLayout } from "./ClientLayout";// 👈 Header 컴포넌트 불러오기

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BookTree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="bg-[#F4F4F4]">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F4F4F4]`}>
        <Header /> {/* 👈 공통 헤더 */}
        <main className="w-full max-w-full px-5">{children}</main>
      </body>
    </html>
  );
}
